services:
  booking-service:
    build: ./booking-service
    image: booking-service
    container_name: booking-service
    restart: unless-stopped
    ports:
      - '7001:7001'
    # volumes:
    #   - ./dist:/app/dist
    #   - ./node_modules:/app/node_modules
    #   - ./package.json:/app/package.json
    networks:
      - app-network
    links:
      - db
  db:
    image: mongo:4.4.4
    container_name: db
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - '7003:27017'
  pricing-service:
    build: ./pricing-service
    image: pricing-service
    container_name: pricing-service
    restart: unless-stopped
    ports:
      - '7000:7000'
    # volumes:
    #   - ./dist:/app/dist
    #   - ./node_modules:/app/node_modules
    #   - ./package.json:/app/package.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
