services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: pricing-service
    container_name: pricing-service
    restart: unless-stopped
    ports:
      - '7000:7000'
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
