services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - '7001:7001'
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    networks:
      - app-network
    links:
      - db
  db:
    image: mongo:4.4.4
    container_name: db
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - '7003:27017'

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
